name: Export Oracle Image

on:
  workflow_dispatch:

jobs:
  export-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull Oracle image
        run: |
          docker pull smarsbhu/proj1-dwh-cluster:oracle-oltp-smars-1.1.1oracle

      - name: Save image to tar
        run: |
          docker save smarsbhu/proj1-dwh-cluster:oracle-oltp-smars-1.1.1oracle -o oracle.tar

      - name: Split tar into 5GB chunks
        run: |
          split -b 5120m oracle.tar oracle.tar.part.

      - name: Upload artifacts (all chunks)
        uses: actions/upload-artifact@v3
        with:
          name: oracle-image-parts
          path: oracle.tar.part.*
          retention-days: 5
